Fix Linux CPU Tests CMAKE
* for install protobuf 3

* for docker to build proto3

* fix path

* dependencies for protobuf3

* remove recursively

* target_compile_features require CMake 3.1.0

Ref: https://cmake.org/cmake/help/v3.1/release/3.1.0.html

* no need to make check here

* require CMake 3.1+

* add ${CMAKE_DL_LIBS} for -ldl

* [bugfix] chase version to tensorflow/workspace.bzl

* it contains int main()

* there's no add_test() in tensorflow/contrib/cmake/

* fix error from tensorflow-pull-requests-cpu

ERROR: missing input file '//tensorflow/core/ops/compat:update_ops.cc'.