wrong code in programmer's guide in Variable Section
In Programmer's guide Variable section
 the assignment variable is a `tf.Tensor` and should use `assignment.op.run()` instead of `assignment.run()`
Otherwise, this code would produce an error:
```
AttributeError: 'Tensor' object has no attribute 'run'
```
Or we can use sess.run(assignment) to finish this assignment operation